# For Nginx
namespace: bz-appy
nginx:
  replicas: 1
  image: beny14/nginx_static:latest
  service:
    nodePort: 30000
  hpa:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 50
  ingress:
    host: nginx.local  # Ensure this is set correctly
  pvc:
    storage: 1Gi