# For Nginx
namespace: benyz
nginx:
  replicas: 1
  image: beny14/nginx_static:latest

  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50

  ingress:
    host: nginx.local  # Ensure this is set correctly

  pvc:
    storage: 1Gi
