apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{ .Values.namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"  # Mark as internal load balancer
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer
