apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: bz-jenkins
roleRef:
  kind: ClusterRole
  name: cluster-admin  # You may choose a more restricted role if necessary
  apiGroup: rbac.authorization.k8s.io