apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  # Adjust the name to reflect your needs
  name: jenkins-manager-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: bz-jenkins
roleRef:
  kind: ClusterRole
  name: jenkins-manager
  apiGroup: rbac.authorization.k8s.io
