apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: bz-appy
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000  # Customize this if needed
  selector:
    app: nginx
