apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pvc-access
  namespace: bz-appy
  annotations:
    "helm.sh/hook": "pre-install"
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles" , "secrets"]
  verbs: ["patch"]