{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.roleBinding.name }}
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: bz-jenkins  # Make sure this matches the service account namespace
roleRef:
  kind: Role
  name: {{ .Values.rbac.role.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
