apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  namespace: bz-appy  # Ensure the namespace matches the PVC namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /home/bz/Desktop/kube_repo/k8s/nginx/nginx-chart/templates/nginx-pvc.yaml  # Update the path if needed
