apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-scaledobject
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: nginx-deployment
  minReplicaCount: {{ .Values.scaledobject.minReplicas }}
  maxReplicaCount: {{ .Values.scaledobject.maxReplicas }}
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "{{ .Values.scaledobject.cpuUtilization }}"
