apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: benyz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: beny14/nginx_static:latest
        ports:
        - containerPort: 4000
        volumeMounts:
          - name: nginx-storage
            mountPath: /usr/share/nginx/html
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 4000
          initialDelaySeconds: 60
          timeoutSeconds: 5
      volumes:
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-pvc
