{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.role.name }}
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "secrets"]
    verbs: ["get", "list", "create"]  # Ensure 'create' is included here
{{- end }}
