apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-pvc-access
  namespace: bz-appy
  annotations:
    "helm.sh/hook": "pre-install"
subjects:
- kind: ServiceAccount
  name: default
  namespace: bz-jenkins
roleRef:
  kind: Role
  name: pvc-access
  apiGroup: rbac.authorization.k8s.io
