apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 30000
      nodePort: {{ .Values.nginx.service.nodePort | default 30002 }}
  type: NodePort
