apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80  # This should match the containerPort in the deployment
      targetPort: 80  # This should also match the containerPort
      nodePort: {{ .Values.nginx.service.nodePort | default 30002 }}
  type: NodePort
