apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  namespace: benyz
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /usr/share/nginx