# templates/pvc-access.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pvc-access
  namespace: bz-appy
rules:
  - apiGroups: [""]                     # Core API group for basic resources like PVCs
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]                  # API group for apps resources, including deployments
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "delete"]