apiVersion: v1
kind: Secret
metadata:
  name: jenkins-token
  namespace: jenkins
  annotations:
    kubernetes.io/service-account.name: jenkins
    kubernetes.io/service-account.uid: "17cc5a71-bd85-4f73-ba58-d93d984bfc8a"
type: kubernetes.io/service-account-token

