apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /home/bz/Desktop/kube_repo/k8s/app/app-data  # Ensure this path exists on the node
