apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      {{- if .Values.app.service.nodePort }}
      nodePort: {{ .Values.app.service.nodePort | default 30001 }}
      {{- end }}
  type: {{ .Values.app.service.type | default "ClusterIP" }}
