apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: {{ .Values.app.image }}
          volumeMounts:
            - name: app-storage
              mountPath: /data  # Path inside the container
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-pvc