apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
  namespace: benyz  # Ensure the namespace matches the PVC namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /home/bz/Desktop/kube_repo/k8s/app/app-chart/templates/app-pvc.yaml  # Update the path if needed
