apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-deployment
  minReplicas: {{ .Values.app.hpa.minReplicas | default 1 }}
  maxReplicas: {{ .Values.app.hpa.maxReplicas | default 5 }}
  targetCPUUtilizationPercentage: {{ .Values.app.hpa.targetCPUUtilizationPercentage | default 50 }}
