namespace: benyz
app:
  replicas: 1
  image: beny14/python_app:latest
  service:
    type: NodePort
    nodePort: 30001
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
  ingress:
    host: app.local
  pvc:
    storage: 1Gi
  scaledobject:
    minReplicas: 1
    maxReplicas: 5
    cpuUtilization: "50"
