apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hpa-manager-binding
  namespace: bz-appy
subjects:
- kind: ServiceAccount
  name: default  # Replace with the service account your Jenkins pod uses
  namespace: bz-jenkins  # Replace with the namespace where Jenkins is running
roleRef:
  kind: Role
  name: hpa-manager
  apiGroup: rbac.authorization.k8s.io
