apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  # A name for the ClusterRoleBinding
  name: impersonate-serviceaccount-binding
subjects:
  - kind: User
    name: "system:node:ip-10-44-34-200.us-east-2.compute.internal"  # Jenkins worker node
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: impersonate-serviceaccount
  apiGroup: rbac.authorization.k8s.io
