apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hpa-manager-binding
  namespace: bz-appy  # Ensure the binding is applied in the right namespace
subjects:
  - kind: ServiceAccount
    name: default  # Replace with your Jenkins service account name if different
    namespace: bz-jenkins  # Ensure this is the correct namespace for your Jenkins service account
roleRef:
  kind: Role
  name: hpa-manager
  apiGroup: rbac.authorization.k8s.io
