apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bz-appy
  name: hpa-manager
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    verbs: ["get", "list", "delete"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "delete"]
  - apiGroups: [""]
    resources: ["services", "persistentvolumeclaims"]
    verbs: ["get", "list", "delete"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: bz-appy
  name: secrets-access
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
