apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bz-appy  # Ensure the role is applied in the right namespace
  name: hpa-manager
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    verbs: ["get", "list", "delete"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "delete"]  # Added delete permission for HPA
  - apiGroups: [""]
    resources: ["services", "persistentvolumeclaims"]
    verbs: ["get", "list", "delete"]
