
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer
