apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # Exps on a specific NodePort (external access)
    - name: jnlp
      protocol: TCP
      port: 50000
      targetPort: 50000
      nodePort: 30050  # Expose JNLP port on specific NodePort
  type: NodePort
