namespace: bz-appy
nginx:
  replicas: 1
  image: beny14/python_app:latest

  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50

  ingress:
    host: app.local

pvc:
  storage: 1Gi
