namespace: bz-appy
app:
  replicas: 1
  image: beny14/python_app:latest
  service:
    type: LoadBalancer
  ingress:
    host: app.local
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
pvc:
  storage: 1Gi
