apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-deployment
  namespace: bz-argocd
spec:
  project: app
  source:
    repoURL: 'https://github.com/beny1221g/k8s.git'
    targetRevision: HEAD
    path: k8s/app/app-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bz-appy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
