apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  storageClassName: standard


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pvc
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.pvc.storage }}
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /home/tmp/jenkins/app/app-py
