apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: {{ .Values.app.service.type | default "LoadBalancer" }}
